### ISSUE TITLE
[Bug]竹子的放置问题

### ISSUE THREAD

**Issue by Zhiyu-Yang** [Snownee/Cuisine#10]
用竹子右击野生竹子会导致新放置的竹子位于其后方，如图所示。图1为右击后，图2 为右击前。
![2018-10-01_21 15 34](https://user-images.githubusercontent.com/38756860/46303065-6f446e00-c5dd-11e8-9d3b-5e3c1a81ffef.png)
![2018-10-01_21 15 28](https://user-images.githubusercontent.com/38756860/46302946-1aa0f300-c5dd-11e8-893b-0488410ebcac.png)

**Comment by Snownee** [comment]
无法复现，请尝试移除Optifine

**Comment by Zhiyu-Yang** [comment]
![default](https://user-images.githubusercontent.com/38756860/46333631-98074a80-c653-11e8-9b50-6de5bfa07124.png)
![default](https://user-images.githubusercontent.com/38756860/46333634-a2294900-c653-11e8-87b8-465037167fea.png)
![default](https://user-images.githubusercontent.com/38756860/46333647-abb2b100-c653-11e8-8e78-71a3fbbc3e01.png)
![default](https://user-images.githubusercontent.com/38756860/46333658-b5d4af80-c653-11e8-93b2-caa6b4c656d8.png)
![default](https://user-images.githubusercontent.com/38756860/46333664-bf5e1780-c653-11e8-9d6e-271f22460ef7.png)
mod列表如上。该bug在存档内复现过多次。

**Comment by SihenZhang** [comment]
OptiFine 不开源，所以我们也没办法提供修复方案，sry

**Comment by Snownee** [comment]
考虑反馈给Optifine: https://github.com/sp614x/optifine/issues
