### ISSUE TITLE
Suggestion - Config option to not start the game with the manual

### ISSUE THREAD

**Issue by DWX12** [Snownee/Cuisine#12]
Might be an oversight, but a config option to start the game without a manual is standard in most mods.

Will also add that adding in the default values or settings in your config file is also common practice and would be nice to have. Such as [Default: CropsGenRate=0] as an example or something similar.

Thanks for the great mod and the time and effort you put into it.

**Comment by 3TUSK** [comment]
Can you see the default value for each config options in the config GUI? In Esc-menu, click "Mod Options...", find "Cuisine", then click "Config" on the bottom-left and you will see it.

**Comment by 3TUSK** [comment]
Besides that - yes, that is an oversight. I sometimes get annoyed with those books, too.

**Comment by Snownee** [comment]
Will be added in 0.3.0
