### ISSUE TITLE
Crash when crafting cuisine recipes with Refined Storage on a server

### ISSUE THREAD

**Issue by EpicSquid** [Snownee/Cuisine#15]
Link to the Crash Log:
https://pastebin.com/1HzF3DeP

This appears to be an issue where Cuisine is trying to access a client-only class on the server side. Let me know if you need anything else.

**Comment by 3TUSK** [comment]
Known issue, fixed in revision 0d887e0265b0d636dc6b23b9012ab73bedcb37d5. Pending next new release, and it would take a while because of the amount of API re-design and internal changes.
