### ISSUE TITLE
Firepit suggestions

### ISSUE THREAD

**Issue by Waynekosimoto** [Snownee/Cuisine#17]
- [ ] Fuel (GUI?)
- [ ] Easily removable wok / barbeque rack
- [ ] Lighting system (flint and steel)

**Comment by 3TUSK** [comment]
1. GUI is against our design to a certain extent. I am imagining that the pit is extinguished if there is no fuel to burn. You right click the pit to add fuels. Does lava bucket count as fuel here?
2. One oversight that no one has ever mentioned. Good catch.
3. See 1.; if we do add fuel for fire pit, flint & steel will be definitely the way to go.

**Comment by Waynekosimoto** [comment]
When I envision a GUI-less firepit I imagine a craftable empty firepit ( a circle of stones), and you can right click logs into the firepit, the amount of wood would be shown visually with 3d logs. If the fire goes out you would need to relight it (flint and steel). Fuel would simply be wood and would burn over time. The firepit would be reusable.

**Comment by Waynekosimoto** [comment]
Also, I love the mod btw, it's exactly what I've wanted.

**Comment by Snownee** [comment]
Thanks for suggesting! Some suggestions you mentioned are already in our plan and will implemented in the future!

**Comment by 3TUSK** [comment]
> Reopen for future reference.
