### ISSUE TITLE
胡萝卜种植的问题（显示紫黑方块）

### ISSUE THREAD

**Issue by NONO219** [Snownee/Cuisine#27]
![2018-12-06_15 15 52](https://user-images.githubusercontent.com/40620243/49693176-aa978600-fba6-11e8-8453-632070a6f224.png)

问题如图。这个存档本是纯净存档，也就是为什么旁边有一些没问题的胡萝卜苗。但是自从装了cuisine mod之后，播种下的所有胡萝卜都变成了紫黑方块。我现在所有的模组里面与胡萝卜有联系的只有这个mod。

望解决~

**Comment by Snownee** [comment]
头一回见到这个问题，请确定只安装Cuisine的时候该问题是否存在。
