### ISSUE TITLE
Spice of life compat

### ISSUE THREAD

**Issue by lobbienjonsji** [Snownee/Cuisine#28]
It would be amazing if this mod was compatible with spice of life/spice of life carrot edition

**Comment by 3TUSK** [comment]
But what do you mean by "compatible"? It could mean many things, so I just want to double check before writing anything.

**Comment by lobbienjonsji** [comment]
Spice of life carrot edition can increase the max health of a player, whenever they discover and eat a certain number of different food items (the maximum hp caps out at ten bonus hearts by default). The wok can create many different dishes, but spice of life does not recognize them as food. Of course changing this would make getting bonus hearts way easier, but it would work well with, for example, the unhealthy dying mod, that reduces the players health whenever they die. That would make for an interesting challenge. Compatibility with spice of live would simply mean, that eating too much of the same dish makes it less effective.

**Comment by 3TUSK** [comment]
> Compatibility with spice of live would simply mean, that eating too much of the same dish makes it less effective.

Now it falls to the issue of "what makes two dishes the same, and what makes two dishes different"...

**Comment by Winddbourne** [comment]
I actually am using spice of life carrot edition along with unhealthy dying in a pack to create a sliding health scale for players . . . and this was an important question to me when I saw the mod . . . What does constitute a new Dish. Especially when the pack also includes other mods that add food to the game. But I am very interested in the potion/alchemy aspect of cooking in this mod. 

My answer is that a new food should be counted based on each separate ingredient that is registered as it's own food. If I have Pam's Harvestcraft and I somehow want to mix together two full meals in some ridiculous way that's great . . . but when I eat the dish it should mark off BOTH of those items as eaten and contributing to gaining hearts just as if I had eaten them separately. 

If I cook up a dish where I've already sampled all of the ingredients then I guess that dish has already been eaten and contributed to adding hearts and nothing more can be gained. 

I admit the solution is a bit clumsy . . . but there is no way I could balance my mod pack if there were infinite food variations. I just removed Butchercraft and I found this while looking for a replacement . . . 

Previously I had about 1500 unique foods players could cook; multiplying that out for everything you COULD cook in my pack using this mod would be insane.
