### ISSUE TITLE
[Request] Compact with Tough As Nails Purified Water

### ISSUE THREAD

**Issue by Kiyaku** [Snownee/Cuisine#30]
Heya,
loving the mod so far! 

Was wondering if there could be some compatibility with Tough As Nails, especially the following: 

- Right clicking certain juices inside basins with a glass bottle should turn into the TAN fruit bottles
- Have rain water collected by basins turn into purified water from TAN (the TAN rain collectors do that, but i'd rather disable those and use the basins, for early game clean water)

Think that's something that could be added? 

Cheers,
SC

**Comment by Snownee** [comment]
Thanks for your suggestions! I will tell you why I do not take your suggestion:

- Making TaN juices requires one sugar but in Cuisine it is not. And you can simply drink juice from Cuisine to get the same effect.
- Basin is too cheap comparing with rain collector. And I think the ability that rain collector can purify water is partially comes from the string (filter) from its recipe.

And yes some compatibility features with purified water have already in our plan, and will be implemented in the future!

**Comment by Kiyaku** [comment]
Appreciate the reasoning behind your decision! Looking forward to the purified water compat you mentioned in the future :)
