### ISSUE TITLE
Chopping Board

### ISSUE THREAD

**Issue by Fortist** [Snownee/Cuisine#31]
Can you add a configuration to the wood chopping plank number?
So instead of 6 I can change it to another number?

Some logs arnt recognized, like Rubber (Industrial Foregoing) and Menril (Integrated Dynamics)

Also, you cannot offhand and place an Item, which is understandable since you use both left and right click to slice/dice whatever is on it.

**Comment by Snownee** [comment]
Thanks for your suggestion!
https://minecraft.curseforge.com/projects/cuisine/files/2659108

**Comment by Fortist** [comment]
That was fast, Thank you
