### ISSUE TITLE
Chopping Board Part 2

### ISSUE THREAD

**Issue by Fortist** [Snownee/Cuisine#39]
So, I have NoTreePunching a mod that uses saws (which extends itemAxe, I assume) to craft planks from logs in the crafting table. 

![choppin2](https://user-images.githubusercontent.com/5784537/52299143-aabbc400-2952-11e9-95f7-888cb3db26bf.png)

However, with Cuisine added, it would create a chopping board with the saw above log recipe.
I had a problem where I tried to disable the chopping board recipe with crafttweaker only for it to not work as intended, even using all the nbt data/tag data/whatever.
```
recipes.remove(<cuisine:chopping_board>);
recipes.remove(<cuisine:chopping_board>.withTag({BlockEntityTag: {cover: {id: "minecraft:log", Count: 1 as byte, Damage: 0 as short}}}));
```

So I took a drastic measure and just deleted the recipe json in the jar itself to 'fix' the recipe conflict, It works in the way that I can now make planks with saw in the crafting table, but due to some underlying code the axe+log recipe still shows up, despite it not actually working.
![choppin](https://user-images.githubusercontent.com/5784537/52298444-f66d6e00-2950-11e9-97f1-43c311c5e2c9.png)

On another side, there doesnt need to be a chopping board per log, and I have a mod that adds a log that is "white" in texture but changes colors due to NBT or whatever and they all show up as white chopping boards. A little more control over what becomes a chopping board would be nice.

**Comment by 3TUSK** [comment]
1. In fact, the only reliable way to remove a recipe is to remove it by its recipe ID. Either remove by input or output is practically unreliable. Also it is strongly discouraged to tamper the jar - it makes impossible for us to make sure that the jar is indeed from us.  
See [CraftTweaker Documentation](https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Recipes/Crafting/Recipes_Crafting_Table/#remove-by-name) for details about `recipes.removeByRecipeName`.
```java
// This is guaranteed working.
recipes.removeByRecipeName("cuisine:chopping_board");
```
2. That issue of JEI displaying ghost recipe will be investigated.
3. Which mod is that colored log come from anyway? I would assume it is something wrong on Cuisine's side, but I need to know the details.
4. As for "a little more control over what becomes a chopping board" - this will be considered.

**Comment by Fortist** [comment]
The mod in question is "Natural Pledge." The Iridescent Logs, to be exact.   Also, I have no idea what that means, Snow.
But to show you what I mean, this is just the two mods together, no crafttweaking.

![2019-02-12_21 39 31](https://user-images.githubusercontent.com/5784537/52682842-e2a4a780-2f0e-11e9-8612-608bad36c2b7.png)

I know what Im doing when I mess with .jar files. Especially anything under assets.
But to your credit, using the recipe name in crafttweaker worked, however the ghost recipes still show up.

**Comment by 3TUSK** [comment]
> Iridescent Logs

Will investigate

> however the ghost recipes still show up

Already addressed by https://github.com/Snownee/Cuisine/commit/10de85ab1f627a5f32732af986e33cf6660c85d0 one week ago

**Comment by Snownee** [comment]
Make a chopping board, then make planks by using chopping board and log in world

**Comment by Fortist** [comment]
That has nothing to do with what Im talking about Snow.

**Comment by Snownee** [comment]
I think what your problems are:

1. Chopping board recipe can not be removed (actually can)
   1.1. Chopping board recipe still being shown in JEI after removing (fixed in dev)
2. Cannot make planks if there is a recipe conflict. (yes it is conflict but you can still make planks)

**Comment by 3TUSK** [comment]
![2019-02-13_16 21 58](https://user-images.githubusercontent.com/9113033/52753447-80e64b00-2fab-11e9-955c-7e7211294c5b.png)
@Fortist Fixed in dev
