### ISSUE TITLE
Mods with food tooltips display wrong amount on HC mode

### ISSUE THREAD

**Issue by yikies** [Snownee/Cuisine#42]
Tested this with both Quark's food tooltips and Apple Skin's flashing hunger bar. They both show the default hunger values from foods, but when I actually eat the food it gives me the nerfed hardcore value. Pam's has a similar feature but shows the correct value in both of those mods, so I assume it's on Cuisine's side.

Thanks! Love the mod :)

**Comment by 3TUSK** [comment]
Although I really hope I can fix this - I honestly believe that this is impossible to be fixed. The only thing I can suggest is to disable hardcore food from Cuisine side and only use mods like Hunger Overhaul.

**Comment by yikies** [comment]
no problem my friend, best of luck to you!

**Comment by 3TUSK** [comment]
Gonna close this for now, once I find a proper way to fix this I will re-open this up.
