### ISSUE TITLE
Passable Leaves Compat

### ISSUE THREAD

**Issue by breadguyyy** [Snownee/Cuisine#46]
I'm using a mod called Passable Leaves, but the leaves from this mod aren't affected by it. I posted an issue on that mod's issue tracker and they said they can't do anything if your leaf blocks don't extend blockLeaf. is there any way to remedy this on my end?

**Comment by Snownee** [comment]
No, this is issue with Passable Leaves. There is no need to extend vanilla `BlockLeaves` class. Implementing `isLeaves` is a way as well. In view of the particularity of our leaves we decide not to extend vanilla class. If they cannot come up with a good solution, we can consider to add a compatibility feature.

**Comment by breadguyyy** [comment]
interesting, i made that original issue on their page about 6-7 months ago, and it looks like that mod hasnt been updated in about a year, but I'll put in another issue on their tracker. I'll come back here and let you know if they say no
