### ISSUE TITLE
[0.2.3] Crash when viewing recipe of "generic" items in JEI

### ISSUE THREAD

**Issue by Rikshy** [Snownee/Cuisine#5]
https://paste.dimdev.org/jilutetibo.mccrash

pictures say more than 1000 words:
https://i.imgur.com/olS8GXE.gifv

**Comment by 3TUSK** [comment]
Somehow the ItemStack got malformed data. We will add a fool-proof to related code to prevent crash, but we still need further investigation on how the data gets malformed.
