### ISSUE TITLE
Better with Mods interferes with Cuisine

### ISSUE THREAD

**Issue by MilchLos** [Snownee/Cuisine#52]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2838

Better With Mods Version: 1.12-2.3.20- 1033

Cuisine Version: 0.5.6-build866

Issue Description:
When using the Basins from Cuisine to crush fruits to get Juice, you can't extract the fluid with a glass bottle unless Better With Mods is disabled. Tested with both mods and their dependencies only.

**Comment by 3TUSK** [comment]
Known issue, can't be solve on either side without significantly change game contents from either side.

Workaround is to disable BWM's water bottle tweaks, use this workaround with caution if you care about balance.

There are some discussions regarding the same issue between Railcraft and BWM in [Railcraft/Railcraft#1752](https://github.com/Railcraft/Railcraft/issues/1752#issuecomment-471150298) but there has been no further progress so far. If you want to know the technical details behind the issue, that ticket is a good read.

**Comment by Snownee** [comment]
I think you can disable the module in Better with Mods. Cuisine contains all features the BwM one has.

related codes:
https://gitlab.com/BetterWithMods/1.12/BetterWithMods/blob/1.12/src/main/java/betterwithmods/event/BottleFluidCapability.java
https://github.com/Snownee/Cuisine/blob/master/src/main/java/snownee/cuisine/internal/capabilities/GlassBottleHandler.java

**Comment by MilchLos** [comment]
As far as I can see there is no way to turn off the water bottle tweak of BWM.

**Comment by Snownee** [comment]
Forge designing issue. Cannot fix
