### ISSUE TITLE
Dish data is lost if player is in creative mode on a multiplayer server

### ISSUE THREAD

**Issue by YeJenMing** [Snownee/Cuisine#54]

**Comment by 3TUSK** [comment]
什么冲突？怎么冲突？显示的什么？有没有崩溃？有没有日志文件？

**Comment by YeJenMing** [comment]
图标会在物品栏中显示一段时间然后消失




------------------ 原始邮件 ------------------
发件人: "Urey. Xue"<notifications@github.com>; 
发送时间: 2019年6月20日(星期四) 凌晨3:15
收件人: "Snownee/Cuisine"<Cuisine@noreply.github.com>; 
抄送: "&#x1F319;"<2698213729@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Snownee/Cuisine] 与多人游戏的显示冲突 (#54)




什么冲突？怎么冲突？显示的什么？有没有崩溃？有没有日志文件？

**Comment by 3TUSK** [comment]
什么的图标？做好的菜的吗？

> 如果你能一次性全部说清楚的话……

**Comment by YeJenMing** [comment]
菜品在装进盘后 再打开背包菜品会消失



------------------ 原始邮件 ------------------
发件人: "Urey. Xue"<notifications@github.com>; 
发送时间: 2019年6月20日(星期四) 凌晨3:17
收件人: "Snownee/Cuisine"<Cuisine@noreply.github.com>; 
抄送: "&#x1F319;"<2698213729@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Snownee/Cuisine] 与多人游戏的显示冲突 (#54)




什么的图标？做好的菜的吗？
  
如果你能一次性全部说清楚的话……

**Comment by 3TUSK** [comment]
已知问题，暂时没有好的解决办法，你应该是在创造模式吧？

**Comment by YeJenMing** [comment]
对





------------------ 原始邮件 ------------------
发件人: "Urey. Xue"<notifications@github.com>; 
发送时间: 2019年6月20日(星期四) 凌晨3:22
收件人: "Snownee/Cuisine"<Cuisine@noreply.github.com>; 
抄送: "&#x1F319;"<2698213729@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Snownee/Cuisine] 与多人游戏的显示冲突 (#54)




已知问题，暂时没有好的解决办法，你应该是在创造模式吧？

**Comment by YeJenMing** [comment]
所以是说在创造模式下才会吗




------------------ 原始邮件 ------------------
发件人: "Urey. Xue"<notifications@github.com>; 
发送时间: 2019年6月20日(星期四) 凌晨3:22
收件人: "Snownee/Cuisine"<Cuisine@noreply.github.com>; 
抄送: "&#x1F319;"<2698213729@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Snownee/Cuisine] 与多人游戏的显示冲突 (#54)




已知问题，暂时没有好的解决办法，你应该是在创造模式吧？

**Comment by 3TUSK** [comment]
和 Minecraft 自身的一个设定有关系。如果是 Cuisine 自己修复这个问题需要把菜的底层重写……

**Comment by 3TUSK** [comment]
以防万一把标题改成英文的了，这样后来的人至少还能搜到。

**Comment by Snownee** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/4580
