### ISSUE TITLE
Conflict with MetalChests mod and Electroblob's Wizardry

### ISSUE THREAD

**Issue by kreezxil** [Snownee/Cuisine#58]
Your mod when installed alongside Metalchests and Electroblob's Wizardry causes a dedicated server to kick a player when they try to pick up a metal chests upgrade. The exception appears to be thrown by ebwizardry, but on the 3rd line of the trace cuisine is mentioned. Removing cuisine stops the  exception from being thrown and prevents the player from being needlessly kicked.

Original report at https://github.com/Electroblob77/Wizardry/issues/157

**Comment by Snownee** [comment]
Update tbone
