### ISSUE TITLE
filling up the wok causes blocks from other mods to render weirdly

### ISSUE THREAD

**Issue by majijn** [Snownee/Cuisine#63]
the block ive noticed it with are the flames from arcane archives' brazier of hoarding

when a filled wok is in view of the camera the flames go wonky

**Comment by Snownee** [comment]
GIF plz

**Comment by majijn** [comment]
dunno how to make gifs of the game, i do however have screenshots
![2019-10-27_02 51 09](https://user-images.githubusercontent.com/18368034/67628589-36baa680-f868-11e9-8547-6d52d9f5a9b5.png)
![2019-10-27_02 52 38](https://user-images.githubusercontent.com/18368034/67628590-36baa680-f868-11e9-8ce1-d8f0116a53f1.png)

**Comment by Snownee** [comment]
![TIM图片20191027150041](https://user-images.githubusercontent.com/16059084/67630981-9ba6e880-f8ca-11e9-9ce9-a08c89ecf49c.png)

**Comment by majijn** [comment]
is that the fix or it not being reproduced in your instance?

**Comment by Snownee** [comment]
I cannot reproduce
