### ISSUE TITLE
Dynamic trees and Better Foliage support 

### ISSUE THREAD

**Issue by Null-151** [Snownee/Cuisine#64]
* Minecraft Version: 1.12.2
 * Mod Version: 0.5.15 build 902

Resumitting this issue since the other one just didn't go anywhere, is compatibility with Dynamic Trees considered ? 
Also, the new leaves don't work with Better Foliage's extra leaves, and BF doesn't have a config to add specific blocks to take effect on

**Comment by Snownee** [comment]
Support for Dynamic Trees is too complicated. Fruit trees are nor our main theme. I do not want to spend too much time on it.

> BF doesn't have a config to add specific blocks to take effect on

Wrong. [This](https://github.com/octarine-noise/BetterFoliage/pull/227/files) is the config. You can add it by yourself

BF guys do not maintain their project. I cannot do more things
