### ISSUE TITLE
[Question] crude sugar?

### ISSUE THREAD

**Issue by astersp** [Snownee/Cuisine#65]
* Minecraft Version: 1.12.2
 * Mod Version: Cuisine-0.5.15-build902.jar

how do i make crude sugar? i put the sugar cane into the basin and made it into the sugarcane juice thing but when i heated up the basin (im using one of the earthen basins and i tried using both fire and lava underneath it) it didn't make the sugar. did i not wait long enough? or am i doing something wrong?

thank you in advance!

**Comment by Snownee** [comment]
I do not think you did anything wrong. Can you see the recipe in JEI?

**Comment by astersp** [comment]
i can but i don't think i understand it. what does the arrow and the empty basin mean?
[picture](https://i.imgur.com/pWQWyEG.png)

**Comment by 3TUSK** [comment]
“Auto-pop-up”.
