### ISSUE TITLE
Far From Home Compatibility issue

### ISSUE THREAD

**Issue by SmokeWeebEveryday** [Snownee/Cuisine#66]
When I try to create a world with the Far From Home Worldgen option, the ground is covered in bamboo shoots in every location possible. I'm not sure if this is an issue with Cuisine or Far From Home, but I was wondering if there was some way to just disable bamboo?

**Comment by 3TUSK** [comment]
#60. Looks like it is not just a single case…
@Snownee

**Comment by SmokeWeebEveryday** [comment]
Here are some screenshots if you need them
https://imgur.com/a/lK8wlB0

**Comment by Snownee** [comment]
Please report to Far from Home
