### ISSUE TITLE
Earthen Basin Z-Fighting

### ISSUE THREAD

**Issue by IdrisQe** [Snownee/Cuisine#70]
* Minecraft Version: 1.12.2
 * Mod Version: 0.5.16-907
The Earthen Basin seems to have two textures on it, instead of the grey band just being part of the base texture, and not being offset at all. This leads to massive Z-Fighting issues (it's far worse ingame- less noticable here due to the low gif framerate)

Of note: I am using Optifine. I'm unsure if that may have something to do with it.

![thisisathing](https://user-images.githubusercontent.com/40530630/71043043-46c16a80-20e2-11ea-81e1-a7e31bde227d.gif)

**Comment by 3TUSK** [comment]
> using Optifine

Did you tried without OptiFine?
