### ISSUE TITLE
[BUG?]做出来的菜吃一下就没了，而且添加的饱食度削弱

### ISSUE THREAD

**Issue by SoaliGer** [Snownee/Cuisine#72]
* Minecraft Version:1.12
 * Mod Version:0.5.17
单人测试中一切都正常，但是到了服务器就出现题标所叙述的问题(做出来的菜吃一下就没了，而且添加的饱食度削弱，我尝试修改了hardcore 模块，但依旧)，我试着将客户端的单人游戏配置表移动到伺服器中，但是依旧无效，可见是服务器的问题，如果您能提供一些解决方案再好不过，当然您也可以无视，毕竟这不是模组的问题...

**Comment by SoaliGer** [comment]
![114](https://user-images.githubusercontent.com/59813319/72231533-f95bee80-35f6-11ea-90dc-3b145b103171.png)
这个sh是我的伺服器Mod集合

**Comment by Snownee** [comment]
服务端是？

**Comment by SoaliGer** [comment]
CatServer-a8d129c-universal

**Comment by Snownee** [comment]
早已有的问题，与CatServer不兼容
