### ISSUE TITLE
[Bug Report] Dishes disappear after switching game mode

### ISSUE THREAD

**Issue by RisingInIris2017** [Snownee/Cuisine#74]
#### Mod version:

Cuisine-0.5.17-build909

#### Forge version:

14.23.5.2847

#### Singleplayer or Multiplayer:

Multiplayer, using [CatServer-116209e-universal](https://github.com/Luohuayu/CatServer/releases/tag/20.01.18)
This issue cannot be seen in a singleplayer game.

#### Installed mods:

![](https://user-images.githubusercontent.com/28519848/72961436-02657080-3dec-11ea-93f1-e302c2ebdbe0.png)

## Link to full crash log

This bug does not lead to game crash.

#### How to reproduce:

1. Cook anything and use a plate to get a dish in survival mode.
2. Switch game mode to creative mode.
3. The dish disappeared.
I have a screen record for this issue, here is the link:
https://imgur.com/gallery/XOa2Jcx

**Comment by Snownee** [comment]
Cuisine is not compatible with CatServer
