### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by Taoist-Yu** [Snownee/Cuisine#77]
* Minecraft Version:  1.12.2
 * Mod Version: Cuisine-0.5.19-build912
*  Forge Version: 2847

1. 盘子放地上，吃完后模型不会变回空盘子
2. 装了R键整理后，如果背包里有菜品，整理的时候会自动拿起菜品并且无法整理

**Comment by Snownee** [comment]
读  Issue  要  求
