### ISSUE TITLE
[1.15.2]Do you have a plan?

### ISSUE THREAD

**Issue by EnterFor** [Snownee/Cuisine#79]
I really like this Mod
This makes the food process interesting
Do you have plans for version 1.15?

I hope you won't be angry. I'm just curious

**Comment by Snownee** [comment]
https://github.com/Snownee/Cuisine2 WIP

**Comment by EnterFor** [comment]
> https://github.com/Snownee/Cuisine2 WIP
Nice!!!   I'm looking forward to it!
