### ISSUE TITLE
Culinary Manual only has 1 page

### ISSUE THREAD

**Issue by CircusSeal** [Snownee/Cuisine#81]
* Minecraft Version: 1.12.2
 * Mod Version: Cuisine-0.5.21-build920

I'm not sure if it's supposed to be like this or not, but when I opened the Culinary Manual, there was no way to turn the page. So, all I got from it was a basic welcome, an invitation to Discord, and the option to close. Again, I'm not sure if it's supposed to be like this since I heard it was a WIP, but I decided to go ahead and post this just in case.

**Comment by Snownee** [comment]
install Patchouli
