### ISSUE TITLE
Soy Sauce recipe doesn't work?

### ISSUE THREAD

**Issue by sixtymillionsqrd** [Snownee/Cuisine#83]
In the guidebook it says putting a soybean and water in the Jar will create soy sauce but for me nothing happens. Is this a bug or am I just doing it wrong?

**Comment by Snownee** [comment]
Hello. You are doing wrong but don't mind. Because the design of jar is a failure. Basically it requires some math that I don't want to explain. Feel free to use cheat mode.

**Comment by sixtymillionsqrd** [comment]
Ok I worked this out. It needs exactly 10 soybeans and 1000mb of water or it won't work. Kind of a confusing recipe.
